### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#125]
```text
POETRY_DOTENV_LOCATION="/home/jmerelo/Asignaturas/TFM/My-Many-Reads/prod.env" poetry run uvicorn api:mmr --reload

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at ~/.poetry/lib/poetry/_vendor/py3.10/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
```

I was looking for making the docs, actually...

**Comment by Anglepi** [comment]
Which poetry version do you have?

**Comment by JJ** [comment]
That's not exactly the point. The points are
1. The default configuration should simply work, so the choice should go in that direction.
2. Makefile allows expression of dependencies, and detection of configuration, so either way, it should either fail with a meaningful message (not a Python stack trace) or work their way through dependencies to make it work if it knows how.

**Comment by Anglepi** [comment]
That sounds like a nice to have feature, but right now there are some other priorities and given the deadline I think I won't work on this unless I've finished the rest of stories and have some spare time.

**Comment by JJ** [comment]
"Nice to have" "the default configuration should simply work"?
