### ISSUE TITLE
Aclarar qué no tiene Goodreads

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#126]
Deberías intentar aclarar qué es lo que no tiene GoodReads, más allá del vago
"tiene funcionalidades que no necesito". Si quieres definir tu aplicación como
"GoodReads, pero con..." tienes que ser más preciso.

**Comment by Anglepi** [comment]
Con esto tengo un poco de conflicto la verdad, porque sinceramente goodreads tiene de todo, encuentro poco margen de mejora desde el punto de vista de un usuario lector. Sin embargo, yo como persona que solía leer libros (y espero volver a hacerlo cuando recupere mi paz mental) no era capaz de usar goodreads porque precisamente tiene muchísimas cosas, y las que me parecen más importantes no están bien destacadas.

El margen de mejora que encuentro con respecto a goodreads está relacionado principalmente con la experiencia de usuario, pero no he llegado al punto de desarrollar una interfaz...

Supongo que puedo repasar la sección del estado del arte referente a goodreads y ver si puedo plasmar estos pensamientos sin restarle valor a la existencia de My Many Reads
