### ISSUE TITLE
El usuario editorial no está bien reflejado

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#130]
Para empezar, el mundo del libro es un mundo complejo, que incluye agentes,
editores, márketing y demás. Un agente puede estar interesado en la recepción
crítica de sus representados; una editorial de los que haya publicado, pero la
escala será diferente.
En "problemas" habla sólo de "necesita publicitar", pero no hay ninguna
funcionalidad ni objetivo en la plataforma que permita esas inserciones
publicitarias. De hecho, se critica GoodReads por su opacidad.

Las tendencias pueden ser útiles, pero sólo marginalmente en la editorial, que
estará restringida a los autores con los que tenga contrato o a los manuscritos
que le envíen (generalmente los agentes).

En cuanto a GoodReads, no tengo ni idea de cuál es la funcionalidad que ofrecen
a editoras, pero los autores sí tenemos una página centralizada con comentarios
y demás, así como feed de los blogs que le digamos. El que muestre publicidad
dirigida o no GoodReads no creo que sea una preocupación de la editorial, que
seguramente contratará con alguna central. En todo caso, la referencia a la
inserción de publicidad se me pierde, porque no la veo en ningún sitio en la
descripción del problema, ni hay ninguna referencia a la monetización de la
plataforma (que debería ir en la introducción)

**Comment by Anglepi** [comment]
Diría que esto queda resuelto ya que, a fin de cuentas, venga de donde venga, es un tipo de usuario que va a consumir la información tipo estadísticas de uso y tendencias con el fin de conocer mejor el mercado y apoyar sus decisiones de negocio para incrementar sus propios beneficios.

En otras historias (ya cerradas estos días) he redefinido la descripción y nombre de este tipo de usuario con el fin de no especificar si trabaja como agente de una editorial o se dedica simplemente a la venta de libros, porque es dificil de explicar sin llevar a posibles confusiones, y a fin de cuentas, la información que necesitan es la misma, y los motivos generales por los que la necesitan también son similares.
