### ISSUE TITLE
El estado del arte debería reflejar aspectos parciales del trabajo

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#131]
Tales como
* Frameworks usados
* Tecnologías usadas en general, o disponibles.
* Algoritmos de recomendación

Por otro lado, otras plataformas de blogs permiten publicar las lecturas con un
apuntuación o un hashtag; Wordpress por ejemplo lo permite (seguramente con un
plugin o algún tema).

Por otro lado, hay sitios, como el NY Times, que ofrece API para
desarrolladores: https://developer.nytimes.com/docs/books-product/1/overview
incluyendo las reviews. Sitios de reviews quizás deberían considerarse, o
mencionarse aunque sea de pasada, en el estado del arte.

**Comment by JJ** [comment]
[Este gist](https://gist.github.com/anwarmontasir/bb8ab501163168c5149bb19d1bac95f9) lista todos los APIs de libros y de reseñas que hay por ahí

**Comment by Anglepi** [comment]
Sinceramente pensé en sitios de reviews y similares, es decir, otras plataformas que traten de formar una comunidad centrándose en los libros y no necesariamente estilo goodreads.

No lo hice porque me pareció comparar un poco peras con manzanas, ya que se parecen, pero no son lo mismo, y solo se me ocurriría listarlos como sitios a los que les falta mucha funcionalidad de la que pensaba introducir, por lo que parecería que los añado para transmitir una idea de "mira mi proyecto que bueno es tiene un montón de cosas que estas otras aplicaciones no tienen"

Sin embargo, ahora que lo dices, si que pienso que merece la pena hacer mención a estos sitios, aunque sea por encima y sin hacer una comparativa exhaustiva como la que hay con goodreads y librarything, simplemente porque podrían existir usuarios con los problemas que este proyecto pretende resolver que estén recurriendo a estos otros sitios por algún motivo.

Quedan 5 días para la entrega (ya no estaré de vacaciones) y todavía no tengo completamente claro cuánto me queda identificado como mejorable ni la prioridad que le puedo dar, pero desde luego, esto está en esa lista.
