### ISSUE TITLE
`make doc` no genera las referencias

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#132]
![Captura de pantalla de 2023-06-27 11-40-37](https://github.com/Anglepi/My-Many-Reads/assets/500/bf1926a9-bb45-4cb7-8893-ac261e10e756)

**Comment by Anglepi** [comment]
No puedo reproducirlo, a mi si que me genera las referencias. 

En mi portátil si que me pasó una vez, lo volví a generar y ya fue bien

**Comment by JJ** [comment]
Tendrás que usar las mismas condiciones que en el issue: repo recién descargado.

**Comment by Anglepi** [comment]
Vale, ya si me ocurre y efectivamente volviendo a tirar el comando se genera bien.

Sinceramente, ni idea de latex como para saber a que puede deberse esto

**Comment by JJ** [comment]
Pues tendrás que llamar al comando dos veces desde make doc, ¿no? (con bibtex en medio)

**Comment by Anglepi** [comment]
Es lo que estoy haciendo xDD https://github.com/Anglepi/My-Many-Reads/blob/main/Makefile luego le echo un vistazo y hago alguna prueba mas

**Comment by JJ** [comment]
Generalmente se le llama dos veces después de bibtex: uno para las citas, otra para las referencias.
