### ISSUE TITLE
Los PMVs en la memoria no deberían apuntar al milestone, sino al release

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#134]
Si no se ha hecho un release, no hay un producto.

**Comment by Anglepi** [comment]
No tengo claro cuál es el concepto de release en un proyecto de github. ¿Basta con un commit taggeado? ¿O te refieres a publicar algún tipo de binario?

Este proyecto está pensado para ser usado y gestionado por desarrolladores, por lo que pienso que quizás con un commit taggeado debería bastar, en cuyo caso dado el nivel de desarrollo del proyecto, daría siempre por deprecados todos los PMVs salvo el último desarrollado.

Ando un poco perdido ahora mismo con respecto a cuál es el problema, si no es taggear un commit o tener una rama de release, porque no le veo sentido a empaquetar este proyecto.

**Comment by JJ** [comment]
> No tengo claro cuál es el concepto de release en un proyecto de github. ¿Basta con un commit taggeado? ¿O te refieres a publicar algún tipo de binario?
> 

Lo que sea que diga el milestone. Pero como mínimo, tendrás que tagearlo.

> Este proyecto está pensado para ser usado y gestionado por desarrolladores, por lo que pienso que quizás con un commit taggeado debería bastar, en cuyo caso dado el nivel de desarrollo del proyecto, daría siempre por deprecados todos los PMVs salvo el último desarrollado.

Como te digo, los PMVs tienen una descripción. Hay que sacar (y validar) lo que diga la descripción.
 
> Ando un poco perdido ahora mismo con respecto a cuál es el problema, si no es taggear un commit o tener una rama de release, porque no le veo sentido a empaquetar este proyecto.

El problema es de la documentación. Un milestone en GitHub es simplemente un instrumento para crear un PMV. Desde la documentación será mejor apuntar al PMV, no al milestone. En todo caso, un milestone *pide* un PMV, así que hay que destacarlo (y enlazarlo) de alguna forma.

**Comment by Anglepi** [comment]
He creado las releases y las he enlazado al principio de la descripción de cada PMV al que están asociadas, así que serán visibles desde la documentación también.

Me gusta la idea de que la descripción de cada PMV junto con sus issues sea lo que se vea desde los enlaces de la documentación, así que creo que no voy a actualizar estos enlaces.
