### ISSUE TITLE
Documentation could display some code fragments to support explanation

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#155]
This may require a little extra refactoring of what has been documented so far, but I think it would facilitate comprehension of what's described.

However I don't know if I have the spare time to give this a try and see if I like it, and since it is just an enhancement, it's not a priority

**Comment by JJ** [comment]
No, it should not. You haven't even linked #7, which should be relevant here. You can't assume that the jury understand the specific language you're using, or even any programming language.

**Comment by Anglepi** [comment]
You're right, this would be over specifying, I'll close this.
