### ISSUE TITLE
[US-3] Libraries to manage readings

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#30]
As Sergio the bookworm from MMR,
I want a library of books of my choice,
so I can manage my readings.

---

This means:
- Creating a data structure for a library, that will have a name and a set of books as entries
- Add functionality to add and remove books from a specific library

**Blocked by** #29 

### Related personas

[Reader users](https://github.com/Anglepi/My-Many-Reads/tree/main/docs/md/personas/reader-users.md)

### Tasks
#34 #35

**Comment by Anglepi** [comment]
Created #40 while working on this story

**Comment by JJ** [comment]
Again, not a user story, not closed. Reopen and convert into issue (see #29 )
