### ISSUE TITLE
[TE-3] API required for communication with the application

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#45]
It's necessary to build an API that allows performing all the necessary tasks in the system.

For starters, search for a library good to put in use, and then implement the necessary functions related to the currently existing entities and their respective unit tests.

### Tasks

#46 #47 #48

**Comment by JJ** [comment]
Technical stories need to be linked to user stories anyway.

**Comment by Anglepi** [comment]
> Technical stories need to be linked to user stories anyway.

I can rename this to "Technical epic". The whole point is that I did not create this as a User Story since I remember you told me building an API to access existing business logic is never a user story back in CC
