### ISSUE TITLE
Missing way of access library functionalities

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#48]
Users needs a way to access all functionalities related to libraries from the API. Without this they cannot make use of the functionality
-------

Create the necessary endpoints to manage libraries:

- Create a library, given a name and a user
- Update an existing library name
- Add entries to a library
- Remove entries from a library
- Delete libraries
- Query list of libraries from a specific user
- Query entries of a specific library

**Comment by JJ** [comment]
You're not linking this to any user story, so I must assume it does not add value to the customer.
Additionally, you're not formulating a problem you need to solve, but a solution.
For instance, why would anyone want to remove some book from the list of books read? What value does it add? If it adds value, do you need it in which MVP?

**Comment by JJ** [comment]
> You're not linking this to any user story, so I must assume it does not add value to the customer. Additionally, you're not formulating a problem you need to solve, but a solution. For instance, why would anyone want to remove some book from the list of books read? What value does it add? If it adds value, do you need it in which MVP?

Any reaction to this?
