### ISSUE TITLE
[US-4] Recommendations created by users

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#49]
As Sergio the bookworm from MMR,
I want to create recommendations between of books of my choice,
so I can help other users to decide what to read next.

### Related personas

[Reader users](https://github.com/Anglepi/My-Many-Reads/tree/main/docs/md/personas/reader-users.md)

### Tasks

#57 #58 #59

**Comment by Anglepi** [comment]
Closed as #63 was merged and I missed it

**Comment by JJ** [comment]
Same as #39, not a user story. Why would anyone want to create recommendations? You might want *them* to create recommendations, but if all the business logic you are going to have is to recommend book *that other users have already recommended* there's not a lot of added value, don't you think so?
In this case, I don't even think it should be reopened. It should be simply dropped.
