### ISSUE TITLE
Consider allowing update and removal of user recommendation comments

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#62]

**Comment by JJ** [comment]
Why? Which user story requests this? How does it help the user?

**Comment by Anglepi** [comment]
Nothing yet, it was something that came over my head while doing stuff yesterday, it might be interesting and I didn't want to forget so I created this issue.

The word "consider" is key here, first I'll think about it and then maybe I'll implement it.

**Comment by JJ** [comment]
Well, if it's not in an user story, it's not adding value to any customer. So don't.

**Comment by Anglepi** [comment]
It's not an user story **yet**, it might be in the future, depends on many things

**Comment by JJ** [comment]
If it's not an user story *yet*, it *still* does not add value to the customer. Agile is all about adding value to the customer. So don't. Don't even write an user story retrospectively. Just don't.

**Comment by JJ** [comment]
In relationship with #49 , I still think that everything related to user-created recommendations should be pushed to a later milestone. At any rate, this does not even have a milestone yet.

**Comment by Anglepi** [comment]
In the end, this functionality is not going to be implemented in the near future, so I'm closing this.

**Comment by JJ** [comment]
> In the end, this functionality is not going to be implemented in the near future, so I'm closing this.

Took a while, right?
