### ISSUE TITLE
[TE-7] Data is not persistent

### ISSUE THREAD

**Issue by Anglepi** [Anglepi/My-Many-Reads#85]
It's about time I implemented an actual database with persistency so this project can be productised in the future.

## TASKS
#86 #87 #88 #82

**Comment by JJ** [comment]
Try and formulate issues as a problem. The issue here seems to be you need persistence; but the specific features of this persistence are what will tip the balance in favor of one or the other.

Also, agile development is client-centric. You need to state which user stories are served by this.
