### ISSUE TITLE
Not clear what problem solves the equality operator for libraries

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#93]
It's probably obvious (although there's no user story for it) that an user should not create two libraries with the same name. 

https://github.com/Anglepi/My-Many-Reads/blob/5cbbdb465e96b3b8084626d80d1976b77c2d8593/mmr-backend/library.py#L82-L85

However, that should be enforced at the logic level. There does not seem to be higher-level logic that includes Libraries *and* users and that manages this kind of facts. Other than that, creating this code based on #48 in order to be able to delete libraries, which is again something that does not clearly add value to the user, or does so at this stage of development, is not properly justified.

**Comment by Anglepi** [comment]
As you said, this functionality is not in use and we should control no libraries have repeated names for a given user

**Comment by Anglepi** [comment]
If I find similar situations, not just libraries, I will fix it as well
