### ISSUE TITLE
Only books _for sale in shops_ have ISBN

### ISSUE THREAD

**Issue by JJ** [Anglepi/My-Many-Reads#96]
So compulsorily using a ISBN in all books might need some consideration.

https://github.com/Anglepi/My-Many-Reads/blob/5cbbdb465e96b3b8084626d80d1976b77c2d8593/mmr-backend/book.py#L9

ISBN is not unique; sometimes ISBNs are reused if books are uncatalogued (or for some other reason). If you sell a book in Amazon (or other self-publishing platforms), you might request an ISBN or not. They have an unique ID, however, which they call ASIN. Read all about ISBNs [here](https://en.wikipedia.org/wiki/ISBN)

At any rate, [identifying a book with an (external) ID is not trivial](https://viaf.org/viaf/182212655/), there are several ways to represent it.

**Comment by Anglepi** [comment]
I'll just use my internal Id then, and make sure that the passed value is always a number, not a string
